io:
  interface: "enp4s0" #interface or all

telegram:
  token: "None" #your bot token : get from https://t.me/BotFather , if you dont use it = None
  chatid: "#########" # your chat id : get from https://t.me/chatIDrobot
core:
  rule_type: "parallel" # hierarchy or parallel
path:
  geoip: "./geo/GeoIP.txt"
  geosite: "./geo/GeoSite.txt"